1) Select any free API (the choice is up to you, you can use any from https://rapidapi.com/collection/list-of-free-apis).

In [33]:
import sqlite3

conn = sqlite3.connect('dogs.db')
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS Breeds (
        id INTEGER PRIMARY KEY,
        breed TEXT,
        origin TEXT
    )
''')


cursor.execute('''
    CREATE TABLE IF NOT EXISTS Breeds_img (
        id INTEGER PRIMARY KEY,
        url TEXT,
        img TEXT
    )
''')

conn.commit()
conn.close()

In [29]:
import json
import sqlite3
import requests

url = "https://dog-breeds2.p.rapidapi.com/dog_breeds/group/breed_status/extinct"

headers = {
    "X-RapidAPI-Key": "51b07a06c6mshbaae7fd65806f5cp13da34jsn59c5aa35baa7",
    "X-RapidAPI-Host": "dog-breeds2.p.rapidapi.com"
}

response = requests.get(url, headers=headers)
api_data = response.json()

data = api_data

In [43]:
conn = sqlite3.connect('dogs.db')
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS Breeds (
        id INTEGER PRIMARY KEY,
        breed TEXT,
        origin TEXT
    )
''')

for record in data:
    cursor.execute('''
        INSERT INTO Breeds (id, breed, origin) VALUES (?, ?, ?)
    ''', (record['id'], record['breed'], record['origin']))

conn.commit()
conn.close()

TypeError: tuple indices must be integers or slices, not str

In [36]:
conn = sqlite3.connect('dogs.db')
cursor = conn.cursor()

cursor.execute('''
    CREATE TABLE IF NOT EXISTS Breeds_img (
        id INTEGER PRIMARY KEY,
        url TEXT,
        img TEXT
    )
''')

for record in data:
    cursor.execute('''
        INSERT INTO Breeds_img (id, url, img) VALUES (?, ?, ?)
    ''', (record['id'], record['url'], record['img']))

conn.commit()
conn.close()

In [45]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('dogs.db')
cursor = conn.cursor()

cursor.execute('''
    SELECT Breeds.breed, Breeds.origin, Breeds_img.url, Breeds_img.img
    FROM Breeds
    JOIN Breeds_img ON Breeds.id = Breeds_img.id
''')
data = cursor.fetchall()

conn.close()

df = pd.DataFrame(data, columns=['Breed', 'Origin', 'Link', 'Img'])
df.head()

,Breed,Origin,Url,Img
0,Old English Terrier,England,https://en.wikipedia.org/wiki/Old_English_Terrier,https://upload.wikimedia.org/wikipedia/commons...
1,African hairless dog,Africa,https://en.wikipedia.org/wiki/Abyssinian_sand_...,https://upload.wikimedia.org/wikipedia/commons...
2,Alaunt,Pontic-Caspian Steppe,https://en.wikipedia.org/wiki/Alaunt,https://upload.wikimedia.org/wikipedia/commons...
3,Alpine Mastiff,Swiss and Italian Alps,https://en.wikipedia.org/wiki/Alpine_Mastiff,https://upload.wikimedia.org/wikipedia/commons...
4,Belgian Mastiff,Belgium and the Netherlands,https://en.wikipedia.org/wiki/Belgian_Mastiff,https://upload.wikimedia.org/wikipedia/commons...